---
title: "DataMunging EDA"
author: "Paul Hwang"
output: pdf_document
---


```{r}
library(data.table)

## Loading Data
data.wide <- "C:\\Users\\pauld\\OneDrive\\Desktop\\Data Munging\\Final Project\\DataMungingProject\\MovieCleanFull.csv"
data.long <- "C:\\Users\\pauld\\OneDrive\\Desktop\\Data Munging\\Final Project\\DataMungingProject\\MovieCleanFullLong.csv"
movie.long <- fread(data.long)
movie.wide <- fread(data.wide)
```


1-D EDA
```{r}
library(ggplot2)
library(cowplot)

## Year
mean(movie.wide$Year)
sd(movie.wide$Year)

gp <- ggplot(data = movie.wide, aes(x = Year)) + 
  geom_histogram(color = "black", fill = "lightblue") +
  scale_y_continuous(limits= c(0,25), expand = c(0,0)) +
  theme_light()
gp2 <- ggplot(data = movie.wide, aes(x = Year)) + 
  geom_boxplot(color = "black", fill = "lightblue") +
  theme_void()
plot_grid(gp, gp2, ncol = 1, align = "v", rel_heights = c(4,1), axis = "lr")

ggplot(data = movie.wide, aes(x = Year)) + 
  geom_histogram(aes(y = ..density..), color = "black", fill = "lightblue") + 
  geom_density(alpha = 0.1, fill = "red") +
  scale_y_continuous(limits= c(0,0.03), expand = c(0,0)) +
  theme_light()
```


```{r}
## Runtime
mean(movie.wide$Runtime)
sd(movie.wide$Runtime)

gp <- ggplot(data = movie.wide, aes(x = Runtime)) + 
  geom_histogram(color = "black", fill = "lightblue") +
  scale_y_continuous(limits= c(0,25), expand = c(0,0)) +
  theme_light()
gp2 <- ggplot(data = movie.wide, aes(x = Runtime)) + 
  geom_boxplot(color = "black", fill = "lightblue") +
  theme_void()
plot_grid(gp, gp2, ncol = 1, align = "v", rel_heights = c(4,1), axis = "lr")

ggplot(data = movie.wide, aes(x = Runtime)) + 
  geom_histogram(aes(y = ..density..), color = "black", fill = "lightblue") + 
  geom_density(alpha = 0.1, fill = "red") +
  scale_y_continuous(limits= c(0,0.02), expand = c(0,0)) +
  theme_light()
```

```{r}
library(plotly)
library(plyr)

## Directors
length(unique(movie.wide$Director))

table.dir <- plyr::count(movie.wide$Director)
gp <- ggplot(data = movie.wide, aes(x=Director)) +
  geom_bar(stat = "count",color = "black", fill = "lightblue")
ggplotly(gp)

table.dir[table.dir$freq > 3,]

gp2 <- ggplot(data = table.dir[table.dir$freq > 3,], aes(x=x, y=freq)) +
  geom_bar(stat = "identity",color = "black", fill = "lightblue") +
  theme(axis.text.x = element_text(angle = 90))
ggplotly(gp2)
```


```{r}
## Writers
length(unique(movie.wide$Writer))

table.wri <- plyr::count(movie.wide$Writer)
gp <- ggplot(data = table.wri, aes(x=x, y=freq)) +
  geom_bar(stat = "identity", color = "black", fill = "lightblue")
ggplotly(gp)

table.wri[table.wri$freq > 3,]
gp2 <- ggplot(data = table.wri[table.wri$freq > 3,], aes(x=x, y=freq)) +
  geom_bar(stat = "identity", color = "black", fill = "lightblue")
ggplotly(gp2)
```


```{r}
## Metascore
mean(movie.wide$Metascore, na.rm = TRUE)
sd(movie.wide$Metascore, na.rm = TRUE)

gp <- ggplot(data = movie.wide, aes(x = Metascore)) + 
  geom_histogram(color = "black", fill = "lightblue") +
  scale_y_continuous(limits= c(0,15), expand = c(0,0)) +
  theme_light()
gp2 <- ggplot(data = movie.wide, aes(x = Metascore)) + 
  geom_boxplot(color = "black", fill = "lightblue") +
  theme_void()
plot_grid(gp, gp2, ncol = 1, align = "v", rel_heights = c(4,1), axis = "lr")

ggplot(data = movie.wide, aes(x = Metascore)) + 
  geom_histogram(aes(y = ..density..), color = "black", fill = "lightblue") + 
  geom_density(alpha = 0.1, fill = "red") +
  scale_y_continuous(limits= c(0,0.05), expand = c(0,0)) +
  theme_light()
```

```{r}
## imbdRating
mean(movie.wide$imdbRating)
sd(movie.wide$imdbRating)

gp <- ggplot(data = movie.wide, aes(x = imdbRating)) + 
  geom_histogram(color = "black", fill = "lightblue") +
  scale_y_continuous(limits= c(0,40), expand = c(0,0)) +
  theme_light()
gp2 <- ggplot(data = movie.wide, aes(x = imdbRating)) + 
  geom_boxplot(color = "black", fill = "lightblue") +
  theme_void()

plot_grid(gp, gp2, ncol = 1, align = "v", rel_heights = c(4,1), axis = "lr")

ggplot(data = movie.wide, aes(x = imdbRating)) + 
  geom_histogram(aes(y = ..density..), color = "black", fill = "lightblue") + 
  geom_density(alpha = 0.1, fill = "red") +
  scale_y_continuous(limits= c(0,7.5), expand = c(0,0)) +
  theme_light()
```

```{r}
## imbdVotes
mean(movie.wide$imdbVotes, na.rm = TRUE)
sd(movie.wide$imbdVotes)

gp <- ggplot(data = movie.wide, aes(x = imdbVotes)) + 
  geom_histogram(color = "black", fill = "lightblue") +
  scale_y_continuous(limits= c(0,40), expand = c(0,0)) +
  theme_light()
gp2 <- ggplot(data = movie.wide, aes(x = imdbVotes)) + 
  geom_boxplot(color = "black", fill = "lightblue") +
  theme_void()
plot_grid(gp, gp2, ncol = 1, align = "v", rel_heights = c(4,1), axis = "lr")

ggplot(data = movie.wide, aes(x = imdbVotes)) + 
  geom_histogram(aes(y = ..density..), color = "black", fill = "lightblue") + 
  geom_density(alpha = 0.1, fill = "red") +
  theme_light()
```

```{r}
## boxoffice
mean(movie.wide$BoxOffice, na.rm = TRUE)
sd(movie.wide$BoxOffice, na.rm = TRUE)

gp <- ggplot(data = movie.wide, aes(x = BoxOffice)) + 
  geom_histogram(color = "black", fill = "lightblue") +
  scale_y_continuous(limits= c(0,15), expand = c(0,0)) +
  theme_light()
gp2 <- ggplot(data = movie.wide, aes(x = BoxOffice)) + 
  geom_boxplot(color = "black", fill = "lightblue") +
  theme_void()
plot_grid(gp, gp2, ncol = 1, align = "v", rel_heights = c(4,1), axis = "lr")

ggplot(data = movie.wide, aes(x = BoxOffice)) + 
  geom_histogram(aes(y = ..density..), color = "black", fill = "lightblue") + 
  geom_density(alpha = 0.1, fill = "red") +
  theme_light()
```

```{r}
## Production
length(unique(movie.wide$Production))

table.pro <- plyr::count(movie.wide$Production)
gp <- ggplot(data = table.pro, aes(x=x, y=freq)) +
  geom_bar(stat = "identity", color = "black", fill = "lightblue")
ggplotly(gp)

table.pro[table.pro$freq > 3,]

gp2 <- ggplot(data = table.pro[table.pro$freq > 3,], aes(x=x, y=freq)) +
  geom_bar(stat = "identity", color = "black", fill = "lightblue") +
  theme(axis.text.x = element_text(angle = 90))
ggplotly(gp2)
```

```{r}
library(tidyr)
## Actors
actors.data <- movie.wide[,c("First Actor", "Second Actor", "Third Actor", "Fourth Actor")]
actors <- actors.data %>% pivot_longer(
  cols=c("First Actor", "Second Actor", "Third Actor", "Fourth Actor"),
  names_to = "Actors Type",
  values_to = "Actor"
)

length(unique(actors$Actor))

table.act <- plyr::count(actors$Actor)
gp <- ggplot(data = table.act, aes(x=x, y=freq)) +
  geom_bar(stat = "identity", color = "black", fill = "lightblue")
ggplotly(gp)

table.act[table.act$freq > 3,]

gp2 <- ggplot(data = table.act[table.act$freq > 3,], aes(x=x, y=freq)) +
  geom_bar(stat = "identity", color = "black", fill = "lightblue") +
  theme(axis.text.x = element_text(angle = 90))
ggplotly(gp2)
```


```{r}
## awards
mean(movie.wide$Awards, na.rm = TRUE)
sd(movie.wide$Awards, na.rm = TRUE)

gp <- ggplot(data = movie.wide, aes(x = Awards)) + 
  geom_histogram(color = "black", fill = "lightblue") +
  scale_y_continuous(limits= c(0,30), expand = c(0,0)) +
  theme_light()
ggplotly(gp)

gp2 <- ggplot(data = movie.wide, aes(x = Awards)) + 
  geom_boxplot(color = "black", fill = "lightblue") +
  theme_void()
plot_grid(gp, gp2, ncol = 1, align = "v", rel_heights = c(4,1), axis = "lr")

ggplot(data = movie.wide, aes(x = Awards)) + 
  geom_histogram(aes(y = ..density..), color = "black", fill = "lightblue") + 
  geom_density(alpha = 0.1, fill = "red") +
  theme_light()

movie.wide[movie.wide$Awards > 100,c("Title", "Awards", "imdbRating")]
```

```{r}
## Nominations
mean(movie.wide$Nominations, na.rm = TRUE)
sd(movie.wide$Nominations, na.rm = TRUE)

gp <- ggplot(data = movie.wide, aes(x = Nominations)) + 
  geom_histogram(color = "black", fill = "lightblue") +
  scale_y_continuous(limits= c(0,30), expand = c(0,0)) +
  theme_light()
ggplotly(gp)

gp2 <- ggplot(data = movie.wide, aes(x = Nominations)) + 
  geom_boxplot(color = "black", fill = "lightblue") +
  theme_void()
plot_grid(gp, gp2, ncol = 1, align = "v", rel_heights = c(4,1), axis = "lr")

ggplot(data = movie.wide, aes(x = Nominations)) + 
  geom_histogram(aes(y = ..density..), color = "black", fill = "lightblue") + 
  geom_density(alpha = 0.1, fill = "red") +
  theme_light()

movie.wide[movie.wide$Nominations > 100,c("Title", "Nominations", "imdbRating")]
```
```{r}
## showing deviations for awards and nominations
movie.wide[movie.wide$Awards > 100 | movie.wide$Nominations > 100,
           c("Title", "Awards", "Nominations", "imdbRating")]
movie.wide[movie.wide$Awards > 100 & movie.wide$Nominations > 100,
           c("Title", "Awards", "Nominations", "imdbRating")]
movie.wide[movie.wide$Awards > 100 & movie.wide$Nominations < 100,
           c("Title", "Awards", "Nominations", "imdbRating")]
```

```{r}
## Genre
genre.data <- movie.wide[,c("First Genre", "Second Genre", "Third Genre")]
genres <- genre.data %>% pivot_longer(
  cols=c("First Genre", "Second Genre", "Third Genre"),
  names_to = "Genre Type",
  values_to = "Genre"
)

length(unique(genres$Genre))

table.gen <- na.omit(plyr::count(genres$Genre))

gp <- ggplot(data = table.gen, aes(x=x, y=freq)) +
  geom_bar(stat = "identity", color = "black", fill = "lightblue") +
  scale_y_continuous(limits = c(0,180), expand = c(0,0)) +
  theme(axis.text.x = element_text(angle = 90))
ggplotly(gp)
```

```{r}
## Language
lang.data <- movie.wide[,c("l1","l2","l3","l4","l5","l6","l7")]
language <- lang.data %>% pivot_longer(
  cols=c("l1","l2","l3","l4","l5","l6","l7"),
  names_to = "Language Type",
  values_to = "Language"
)

length(unique(language$Language))

table.lang <- na.omit(plyr::count(language$Language))

gp <- ggplot(data = table.lang, aes(x=x, y=freq)) +
  geom_bar(stat = "identity", color = "black", fill = "lightblue") +
  scale_y_continuous(limits = c(0,260), expand = c(0,0)) +
  theme(axis.text.x = element_text(angle = 90))
ggplotly(gp)

table.lang[table.lang$freq > 3,]

gp2 <- ggplot(data = table.lang[table.lang$freq > 3,], aes(x=x, y=freq)) +
  geom_bar(stat = "identity", color = "black", fill = "lightblue") +
  scale_y_continuous(limits = c(0,260), expand = c(0,0)) + 
  theme(axis.text.x = element_text(angle = 90))
ggplotly(gp2)
```

```{r}
## Country
coun.data <- movie.wide[,c("c1","c2","c3","c4","c5","c6","c7","c8","c9")]
country <- coun.data %>% pivot_longer(
  cols=c("c1","c2","c3","c4","c5","c6","c7","c8","c9"),
  names_to = "Country Type",
  values_to = "Country"
)

length(unique(country$Country))

table.coun <- na.omit(plyr::count(country$Country))
gp <- ggplot(data = table.coun, aes(x=x, y=freq)) +
  geom_bar(stat = "identity", color = "black", fill = "lightblue") +
  scale_y_continuous(limits = c(0,260), expand = c(0,0)) + 
  theme(axis.text.x = element_text(angle = 90))
ggplotly(gp)

table.coun[table.coun$freq > 3,]
gp2 <- ggplot(data = table.coun[table.coun$freq > 3,], aes(x=x, y=freq)) +
  geom_bar(stat = "identity", color = "black", fill = "lightblue") +
  scale_y_continuous(limits = c(0,260), expand = c(0,0)) +
  theme(axis.text.x = element_text(angle = 90))
ggplotly(gp2)
```


2D analysis

```{r}
library(corrplot)
## intro graphics with correlation
movie.numeric <- movie.wide[,c("Year", "Runtime", "Metascore", "imdbRating", 
                               "imdbVotes", "BoxOffice", "Awards", "Nominations")]
res <- cor(movie.numeric, use = "pairwise.complete.obs")
res
corrplot(res, type = "full", order = "original", t1.srt = 45)
```

```{r}
## using long form for genre only
movie.genre <- movie.wide %>% pivot_longer(
  cols=c("First Genre", "Second Genre", "Third Genre"),
  names_to = "Genre Type",
  values_to = "Genre")
movie.genre <- movie.genre[!is.na(movie.genre$Genre),]
```


```{r}
## Metascore Scatterplots "Year", "Runtime", "imdbRating", "imdbVotes", "BoxOffice", "Awards", "Nominations"

cor(movie.wide$Metascore, movie.wide$Year, use = "pairwise.complete.obs")
ggplot(data = movie.wide, aes(y=Metascore, x= Year)) + geom_point() + 
  geom_smooth() + theme_bw()

cor(movie.wide$Metascore, movie.wide$Runtime, use = "pairwise.complete.obs")
ggplot(data = movie.wide, aes(y=Metascore, x= Runtime)) + geom_point() + 
  geom_smooth() + theme_bw()

cor(movie.wide$Metascore, movie.wide$imdbRating, use = "pairwise.complete.obs")
ggplot(data = movie.wide, aes(y=Metascore, x= imdbRating)) + geom_point() + 
  geom_smooth() + theme_bw()

cor(movie.wide$Metascore, movie.wide$imdbVotes, use = "pairwise.complete.obs")
ggplot(data = movie.wide, aes(y=Metascore, x= imdbVotes)) + geom_point() + 
  geom_smooth() + theme_bw()

cor(movie.wide$Metascore, movie.wide$BoxOffice, use = "pairwise.complete.obs")
ggplot(data = movie.wide, aes(y=Metascore, x= BoxOffice)) + geom_point() + 
  geom_smooth() + theme_bw()

cor(movie.wide$Metascore, movie.wide$Awards, use = "pairwise.complete.obs")
ggplot(data = movie.wide, aes(y=Metascore, x= Awards)) + geom_point() + 
  geom_smooth() + theme_bw()

cor(movie.wide$Metascore, movie.wide$Nominations, use = "pairwise.complete.obs")
ggplot(data = movie.wide, aes(y=Metascore, x= Nominations)) + geom_point() + 
  geom_smooth() + theme_bw()
```

```{r}
## imdbRating Scatterplots "Year", "Runtime", "Metascore", "imdbVotes", "BoxOffice", "Awards", "Nominations"

cor(movie.wide$imdbRating, movie.wide$Year, use = "pairwise.complete.obs")
ggplot(data = movie.wide, aes(y=imdbRating, x= Year)) + geom_point() + 
  geom_smooth() + theme_bw()

cor(movie.wide$imdbRating, movie.wide$Runtime, use = "pairwise.complete.obs")
ggplot(data = movie.wide, aes(y=imdbRating, x= Runtime)) + geom_point() + 
  geom_smooth() + theme_bw()

cor(movie.wide$imdbRating, movie.wide$Metascore, use = "pairwise.complete.obs")
ggplot(data = movie.wide, aes(y=imdbRating, x= Metascore)) + geom_point() + 
  geom_smooth() + theme_bw()

cor(movie.wide$imdbRating, movie.wide$imdbVotes, use = "pairwise.complete.obs")
ggplot(data = movie.wide, aes(y=imdbRating, x= imdbVotes)) + geom_point() + 
  geom_smooth() + theme_bw()

cor(movie.wide$imdbRating, movie.wide$BoxOffice, use = "pairwise.complete.obs")
ggplot(data = movie.wide, aes(y=imdbRating, x= BoxOffice)) + geom_point() + 
  geom_smooth() + theme_bw()

cor(movie.wide$imdbRating, movie.wide$Awards, use = "pairwise.complete.obs")
ggplot(data = movie.wide, aes(y=imdbRating, x= Awards)) + geom_point() + 
  geom_smooth() + theme_bw()

cor(movie.wide$imdbRating, movie.wide$Nominations, use = "pairwise.complete.obs")
ggplot(data = movie.wide, aes(y=imdbRating, x= Nominations)) + geom_point() + 
  geom_smooth() + theme_bw()
```

```{r}
## imdbRating Scatterplots "Year", "Runtime", "Metascore", "imdbVotes", "BoxOffice", "Awards", "Nominations"

ggplot(data = movie.wide, aes(y=imdbRating, x= Metascore, color = Year)) + geom_point() + 
  geom_smooth() + theme_bw()

ggplot(data = movie.wide, aes(y=imdbRating, x= Metascore, color = Runtime)) +
  geom_point() + geom_smooth() + theme_bw()

ggplot(data = movie.wide, aes(y=imdbRating, x= Metascore, color = imdbVotes)) + 
  geom_point() + geom_smooth() + theme_bw()

ggplot(data = movie.wide, aes(y=imdbRating, x= Metascore, color = BoxOffice)) + 
  geom_point() + geom_smooth() + theme_bw()

gp1 <- ggplot(data = movie.wide, aes(y=imdbRating, x= Metascore, color = Awards)) + 
  geom_point() + geom_smooth() + theme_bw()
ggplotly(gp1)

gp2 <- ggplot(data = movie.wide, aes(y=imdbRating, x= Metascore, color = Nominations)) + 
  geom_point() + geom_smooth() + theme_bw()
ggplotly(gp2)

```


```{r}
## model creating Metascore
meta.lm2 <-lm(data = movie.wide, Metascore ~ 1)
meta.lm <- lm(data = movie.wide, Metascore ~ Year + Runtime + 
                 imdbRating + imdbVotes + BoxOffice + Awards + Nominations)
summary(meta.lm)

meta.lm3 <- lm(data = movie.wide, Metascore ~ Year + Runtime + 
                 imdbRating + imdbVotes + BoxOffice + Awards * Nominations)
summary(meta.lm3)

step(meta.lm2, Metascore ~ Year + Runtime + 
                 imdbRating + imdbVotes + BoxOffice + Awards + Nominations, 
     direction = "forward")

step(meta.lm, Metascore ~ 1, direction = "both")

## model creating imdbRating
imdb.lm2 <-lm(data = movie.wide, imdbRating ~ 1)
imdb.lm <- lm(data = movie.wide, imdbRating ~ Year + Runtime + 
                 Metascore + imdbVotes + BoxOffice + Awards + Nominations)
summary(imdb.lm)

step(imdb.lm, imdbRating ~ 1, direction = "backward")
```

```{r}
## model creating imdbRating with only full values
imdb.lm2 <-lm(data = movie.genre, imdbRating ~ 1)
imdb.lm <- lm(data = movie.genre, imdbRating ~ Year + Runtime + 
                 imdbVotes + Awards + Nominations)
summary(imdb.lm)

step(imdb.lm2, imdbRating ~ Year + Runtime + 
                  imdbVotes + Awards + Nominations, 
     direction = "forward")
```

```{r}
## Metascore
gp <- ggplot(data = movie.genre, aes(x = Metascore, fill = Genre)) + 
  geom_histogram(color = "black") +
  scale_y_continuous(limits= c(0,40), expand = c(0,0)) +
  theme_light()
gp

gp2 <- ggplot(data = movie.genre, aes(x = Metascore)) + 
  geom_freqpoly(aes(colour = Genre)) +
  theme_void()
gp2
ggplotly(gp2)

```

```{r}
## imdbRating
gp <- ggplot(data = movie.genre, aes(x = imdbRating, fill = Genre)) + 
  geom_histogram(color = "black") +
  scale_y_continuous(limits= c(0,100), expand = c(0,0)) +
  theme_light()
gp

gp2 <- ggplot(data = movie.genre, aes(x = imdbRating)) + 
  geom_freqpoly(aes(colour = Genre)) +
  theme_void()
gp2
ggplotly(gp2)

```


