---
title: "DataMunging Project"
author: "Paul Hwang"
output: pdf_document
---


```{r}
## library
library(data.table)
library(dplyr)
library(stringr)
library(tidyr)
```



```{r}
## data loading

project.dir <- "C:\\Users\\pauld\\OneDrive\\Desktop\\Data Munging\\Final Project\\DataMungingProject\\imdb_top250_movies.csv"

movie <- fread(project.dir)

```


```{r}
## fixing runtime to numeric

## str(movie$Runtime)

movie$Runtime <- as.integer(sapply(strsplit(movie$Runtime, " "), function(x)(x[1])))

```

```{r}
## fixing genre

## str(movie$Genre)

## checking for unique results

genre.test1 <- strsplit(movie$Genre, ", ")

genre.list <- sort(unique(unlist(genre.test1)))

movie.test <- copy(movie)

## barplot for variation 1 of genre
barplot(table(unlist(genre.test1)))

## creating TF columns

genre.test2 <- movie.test$Genre

## genre.df is a dataframe of booleans containing whether a genre falls in the category
genre.df <- data.frame(matrix(NA, ncol = length(genre.list), nrow = length(movie.test$Genre)))
genre.list2 <- paste0("is", genre.list)
names(genre.df) <- genre.list2


for (i in 1:nrow(genre.df)){
  for (j in 1:ncol(genre.df)){
    genre.df[i,j] <- str_detect(movie.test$Genre[i],genre.list[j])
  }
}

```


```{r}
## genre variation 2, loading things in order
movie.test2 <- copy(movie.test)

genre.split <- movie.test2 %>% 
  separate(Genre, c("First Genre", "Second Genre", "Third Genre")) %>% 
  select(c("First Genre", "Second Genre", "Third Genre"))
```

```{r}
## Main Writer split loading things in order
writer.split2 <- str_split_fixed(movie.test2$Writer, ",", 2)[,1]
names(writer.split2) <- c("Main Writer")
writer.split3 <- sub("\\(.*", "", writer.split2)
```


```{r}
## Actor split loading things in order
movie.test2 <- copy(movie.test)

actor.split2 <- str_split_fixed(movie.test2$Actors, ", ", 4)
colnames(actor.split2) <- c("First Actor", "Second Actor", "Third Actor", "Fourth Actor")
```



```{r}
## fixing language

str(movie$Language)

## checking for unique results

lang.test1 <- strsplit(movie$Language, ", ")

lang.list <- sort(unique(unlist(lang.test1)))

## barplot for variation 1 of genre
barplot(table(unlist(lang.test1)))

## creating TF columns

lang.test2 <- movie.test$Language

## lang.df is a dataframe of booleans containing whether a genre falls in the category
lang.df <- data.frame(matrix(NA, ncol = length(lang.list), nrow = length(movie.test$Language)))
lang.list2 <- paste0("is", lang.list)
names(lang.df) <- lang.list2


for (i in 1:nrow(lang.df)){
  for (j in 1:ncol(lang.df)){
    lang.df[i,j] <- str_detect(movie.test$Language[i],lang.list[j])
  }
}

```

```{r}
## fixing language ver 2
language.split <- str_split_fixed(movie.test2$Language, ", ", 4)[,1:3]
colnames(language.split) <- c("First Language", "Second Language", "Third Language")

## full length
language.split.full <- str_split_fixed(movie.test2$Language, ", ", 7)
colnames(language.split.full) <- c("l1","l2","l3","l4","l5","l6","l7")
```


```{r}
## fixing Country

str(movie$Country)

## checking for unique results

coun.test1 <- strsplit(movie$Country, ", ")

coun.list <- sort(unique(unlist(coun.test1)))

## barplot for variation 1 of genre
barplot(table(unlist(coun.test1)))

## creating TF columns

coun.test2 <- movie.test$Country

## lang.df is a dataframe of booleans containing whether a genre falls in the category
coun.df <- data.frame(matrix(NA, ncol = length(coun.list), nrow = length(movie.test$Country)))
coun.list2 <- paste0("is", coun.list)
names(coun.df) <- coun.list2


for (i in 1:nrow(coun.df)){
  for (j in 1:ncol(coun.df)){
    coun.df[i,j] <- str_detect(movie.test$Country[i],coun.list[j])
  }
}

```

```{r}
## fixing country ver 2
country.split <- str_split_fixed(movie.test2$Country, ", ", 4)[,1:3]
colnames(country.split) <- c("First Country", "Second Country", "Third Country")

## fixing country ver 2 full length
country.split.full <- str_split_fixed(movie.test2$Country, ", ", 9)
colnames(country.split.full) <- c("c1","c2","c3","c4","c5","c6","c7","c8","c9")
```


```{r}
## fixing awards

awards.df <- data.frame(matrix(NA, nrow = 250, ncol = 2))
names(awards.df) <- c("Awards", "Nominations")

gsub("Another.*", "", movie.test$Awards)

## non-oscars split
anothers <- sub(".*Another", "", movie.test$Awards)


## split for wins only
anothers.win <- sub("win.*", "", anothers)
anothers.win2 <- sub(".*nomination.*", "", anothers.win)
anothers.win3 <- as.numeric(anothers.win2)
anothers.win3[is.na(anothers.win3)] <- 0

## split for nominations only
anothers.nom <- sub(".*&", "", anothers)
anothers.nom2 <- sub(".*win.*", "", anothers.nom)
anothers.nom3 <- sub("nomination.*", "", anothers.nom2)
anothers.nom4 <- as.numeric(anothers.nom3)
anothers.nom4[is.na(anothers.nom4)] <- 0



## split for the oscars and other awards
oscnco <- sub("Another.*", "", movie.test$Awards)
oscnco.clean <- sub(".*win.*", "", oscnco)
oscnco.clean2 <- sub(".*nomination.*", "", oscnco.clean)


## split only wins out of named wins
oscnco.wins <- sub(".*Won", "", oscnco.clean2)
oscnco.wins2 <- sub(".*for.*", "", oscnco.wins)
oscnco.wins3 <- sub("([0-9]+).*$", "\\1", oscnco.wins2)
oscnco.wins4 <- as.numeric(oscnco.wins3)
oscnco.wins4[is.na(oscnco.wins4)] <- 0

## split only nominations out of named wins
oscnco.noms <- sub(".*Nominated for", "", oscnco.clean2)
oscnco.noms2 <- sub(".*Won.*", "", oscnco.noms)
oscnco.noms3 <- sub("([0-9]+).*$", "\\1", oscnco.noms2)
oscnco.noms4 <- as.numeric(oscnco.noms3)
oscnco.noms4[is.na(oscnco.noms4)] <- 0

## final combination of wins and nominations

awards.df[,1] <- oscnco.wins4 + anothers.win3
awards.df[,2] <- oscnco.noms4 + anothers.nom4



## checking mechanics for general splits --> require modifications based on what you are checking
# data.frame(anothers, anothers.win2)
# View(data.frame(anothers, anothers.win, anothers.win2))

```

```{r}
## fixing box office dollar amount
boxoff <- gsub('[$,]', "", movie.test$BoxOffice)
movie$BoxOffice <- as.integer(boxoff)

# View(data.frame(boxoff, movie$BoxOffice))
```

```{r}
## fixing voting number to numeric
voteCount <- gsub(",", "", movie.test$imdbVotes)
movie$imdbVotes <- as.integer(voteCount)
```


List to work with are:
1. def change: Writer, Actor, Awards
2. multi version:Genre, Language, Country, 

Any forms of truncation has been done using only the first three categories

```{r}
## removing useless columns (V1,Released, Plot, imdbID, Type, DVD, Website)
movie.final <- select(movie, -c("V1","Released", "Plot", "imdbID", "Type", "DVD", "Website"))

## Replace Writer, Actors, Awards
movie.final$Writer <- writer.split3
movie.final <- select(movie.final, -c(Actors, Awards))
movie.final <- cbind(movie.final, actor.split2, awards.df)

```

```{r}
## version 1 boolean method of genre, language, and country
movie.final1 <- cbind(movie.final, genre.df, lang.df, coun.df)
movie.final1 <- select(movie.final1, -c(Genre, Language, Country))
```

```{r}
## version 2 truncation of first 3
movie.final2 <- cbind(movie.final, genre.split, language.split, country.split)
movie.final2 <- select(movie.final2, -c(Genre, Language, Country))
movie.final2 <- movie.final2 %>% mutate_all(~na_if(.,""))
```

```{r}
## version 2 full
movie.final2full <- cbind(movie.final, genre.split, language.split.full, country.split.full)
movie.final2full <- select(movie.final2full, -c(Genre, Language, Country))
movie.final2full <- movie.final2full %>% mutate_all(~na_if(.,""))
```


```{r}
## version 3 long format of 2
movie.final3 <- copy(movie.final2)


## turning genre into long form
movie.final3 <- movie.final3 %>% pivot_longer(
  cols=c("First Genre", "Second Genre", "Third Genre"),
  names_to = "Genre Type",
  values_to = "Genre")
movie.final3 <- select(movie.final3, -c("Genre Type"))
movie.final3 <- movie.final3[!is.na(movie.final3$Genre),]

## turning language into long form
movie.final3 <- movie.final3 %>% pivot_longer(
  cols=c("First Language", "Second Language", "Third Language"),
  names_to = "Language Type",
  values_to = "Language")
movie.final3 <- select(movie.final3, -c("Language Type"))
movie.final3 <- movie.final3[!is.na(movie.final3$Language),]

## turning language into long form
movie.final3 <- movie.final3 %>% pivot_longer(
  cols=c("First Country", "Second Country", "Third Country"),
  names_to = "Country Type",
  values_to = "Country")
movie.final3 <- select(movie.final3, -c("Country Type"))
movie.final3 <- movie.final3[!is.na(movie.final3$Country),]


## View(movie.final3)
```

```{r}
## version 3 long format of 2full
movie.final3full <- copy(movie.final2full)


## turning genre into long form
movie.final3full <- movie.final3full %>% pivot_longer(
  cols=c("First Genre", "Second Genre", "Third Genre"),
  names_to = "Genre Type",
  values_to = "Genre")
movie.final3full <- select(movie.final3full, -c("Genre Type"))
movie.final3full <- movie.final3full[!is.na(movie.final3full$Genre),]

## turning language into long form
movie.final3full <- movie.final3full %>% pivot_longer(
  cols=c("l1","l2","l3","l4","l5","l6","l7"),
  names_to = "Language Type",
  values_to = "Language")
movie.final3full <- select(movie.final3full, -c("Language Type"))
movie.final3full <- movie.final3full[!is.na(movie.final3full$Language),]

## turning language into long form
movie.final3full <- movie.final3full %>% pivot_longer(
  cols=c("c1","c2","c3","c4","c5","c6","c7","c8","c9"),
  names_to = "Country Type",
  values_to = "Country")
movie.final3full <- select(movie.final3full, -c("Country Type"))
movie.final3full <- movie.final3full[!is.na(movie.final3full$Country),]


## View(movie.final3)
```



```{r}
## Writing CSV files
## printing boolean version
write.csv(movie.final1, "C:\\Users\\pauld\\OneDrive\\Desktop\\Data Munging\\Final Project\\DataMungingProject\\MovieCleanBooleans.csv", row.names = FALSE)

## printing truncated version
write.csv(movie.final2, "C:\\Users\\pauld\\OneDrive\\Desktop\\Data Munging\\Final Project\\DataMungingProject\\MovieCleanTrunc.csv", row.names = FALSE)

## printing long form of truncated version
write.csv(movie.final3, "C:\\Users\\pauld\\OneDrive\\Desktop\\Data Munging\\Final Project\\DataMungingProject\\MovieCleanTruncLong.csv", row.names = FALSE)

## printing full version
write.csv(movie.final2full, "C:\\Users\\pauld\\OneDrive\\Desktop\\Data Munging\\Final Project\\DataMungingProject\\MovieCleanFull.csv", row.names = FALSE)

## printing long form of full version
write.csv(movie.final3full, "C:\\Users\\pauld\\OneDrive\\Desktop\\Data Munging\\Final Project\\DataMungingProject\\MovieCleanFullLong.csv", row.names = FALSE)
```




